export const ARCHIVE_COVER_WIDTH = 1140;
export const ARCHIVE_COVER_HEIGHT = 300;
export const ARCHIVE_COVER_DIMENSIONS_LABEL = `${ARCHIVE_COVER_WIDTH}x${ARCHIVE_COVER_HEIGHT}`;
export const ARCHIVE_COVER_TARGET_ASPECT_RATIO =
  ARCHIVE_COVER_WIDTH / ARCHIVE_COVER_HEIGHT;
export const ARCHIVE_COVER_MIN_ACCEPTED_ASPECT_RATIO =
  ARCHIVE_COVER_TARGET_ASPECT_RATIO - 0.2;
